# To format entire project: cargo +nightly fmt

# Items changed from their defaults:
unstable_features = true
attr_fn_like_width = 120
comment_width = 120
fn_call_width = 120
max_width = 120
single_line_if_else_max_width = 120
group_imports = "StdExternalCrate"

# See https://rust-lang.github.io/rustfmt for description of options.
# You can also obtain a list of options via `rustfmt --print-config current`)
